name: Build EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: windows-latest   # 必须是 Windows，才能生成 exe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build exe with PyInstaller
        run: |
          pyinstaller --onefile your_script.py
        # 输出的 exe 会在 dist/your_script.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-exe
          path: dist/*.exe
